import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { Providers } from "./Providers";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <header className="sticky top-5">
            <NavBar />
          </header>
          <main className="px-14 pt-14 pb-16 max-w-6xl mx-auto">
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
