'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient: QueryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}


      <QueryClientProvider client={queryClient}>

          <div className="App">
                <h2>Ověřeno.cz/Verified.com</h2>
                <button className="button-div"><Link to="createAttestation" href="createAttestation">Create Attestation</Link>
                </button>
                <button className="button-div"><Link to="viewAttestation" href="viewAttestation">View Attestation</Link></button>
                <button className="button-div"><Link to="verifyAttestation" href="verifyAttestation">Verify Attestation</Link>
                </button>

          </div>
      </QueryClientProvider>







      </body>

    </html>
  );
}
